; post:sign_firmware.py

[env:devel]
platform = espressif32
framework = espidf
board = seeed_xiao_esp32c3
board_build.flash_mode = dio
board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts =
lib_deps =
